version: "3"

networks:
  web:
    external: true

services:
  podcloud-api:
    image: $DOCKER_IMAGE
    env_file:
      - .env
    labels:
      - traefik.http.routers.podcloud-api.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.podcloud-api.tls=true
      - traefik.http.routers.podcloud-api.tls.certresolver=lets-encrypt
      - traefik.port=80
      - traefik.http.services.podcloud-api.loadbalancer.server.port=${SERVER_PORT}
    networks:
      - web